function J = Velocity_transformation(l1,l2,th1,th2)
%VELOCITY_TRANSFORMATION
%    J = VELOCITY_TRANSFORMATION(L1,L2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-Oct-2020 19:44:39

t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
J = reshape([-l2.*t3-l1.*cos(th1),-l2.*t4-l1.*sin(th1),0.0,-l2.*t3,-l2.*t4,0.0],[3,2]);
